### ISSUE TITLE
Build failed on `jitpack.io`

### ISSUE THREAD

**Issue by meiMingle** [teletha/reincarnation#12]
https://jitpack.io/com/github/teletha/reincarnation/v1.8.0/build.log
The possible reason is that the release attribute of maven-compiler-plugin is specified as 23 in [`bee/pom.xml`](https://github.com/teletha/bee/blob/master/pom.xml#L909), while the value of the current project is 21.

**Comment by teletha** [comment]
The build tool and dependent library code has been downgraded to Java version 21. I believe the problem is now solved.

Thanks for the report.
